// angular/src/app/dashboard/module-sections/shared/uploader/uploader.component.ts
import { Component, EventEmitter, Output, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-uploader',
  templateUrl: './uploader.component.html',
  styleUrls: ['./uploader.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UploaderComponent {
  _status = [];
  @Input()
  set status(its) {
    this._status = its;
  }
  get status() {
    return this._status;
  }
  @Input() isModule = true;
  @Input() tooltip =
    'Analyze the behaviour of potential malicious samples such as .exe, .dll, .sys, .doc, .pdf, .com and .zip in our sandbox. Max. file size is 20MB.';
  @Input() isDelete = false;
  @Input() allowedUrl = true;
  @Input() uploaderInfo = true;
  @Input() multipleSelect = true;

  @Output() uploadFile = new EventEmitter();
  @Output() uploadUrl = new EventEmitter();
  @Output() closeEmitter = new EventEmitter();
  @Output() removeFile = new EventEmitter();
  @Output() reUploadFile = new EventEmitter();
  @Output() cancelEmitter = new EventEmitter();
  @Output() deleteFile = new EventEmitter();

  url: string;
  isMinified = true;

  toogleMinified() {
    this.isMinified = !this.isMinified;
  }

  shortenFilename(filename) {
    let out = filename;
    if (filename.length > 50) out = filename.substr(0, 40) + '...' + filename.substr(-8, 8);
    return out;
  }

  isUploading(status) {
    return status.some((s) => s.status === 'uploading');
  }

  getNumUploaded(status) {
    return status.filter((s) => s.status === 'complete').length;
  }

  getNumUploading(status) {
    return status.filter((s) => s.status === 'uploading').length;
  }

  getNumError(status) {
    return status.filter((s) => s.status === 'error').length;
  }

  estimatedTime(status) {
    return Math.round(Math.floor(status.map((x) => x.estimatedTime || 0).reduce((a, b) => (a > b ? a : b), 0)));
  }
}

<!-- BUTTONS CHOOSE -->
<div class="uploader">
  <ng-container *ngIf="!url">
    <div class="d-flex align-items-center">
      <input
        class="uploadDefault"
        type="file"
        #uploader
        (change)="uploadFile.emit(uploader.files)"
        name="fileUpload"
        multiple="multipleSelect"
        value=""
      />
      <button (click)="uploader.click()" class="btn btn-outline-primary btn-sm bg-light text-primary">
        <i class="icon-plus-circle-solid mr-1" aria-hidden="true"></i>
        <span>Upload a sample</span>
      </button>
      <button class="btn btn-outline-primary btn-sm bg-light text-primary px-3 ml-2" [ngbTooltip]="tooltip">
        <i class="icon-info" aria-hidden="true"><span style="visibility: hidden">.</span></i>
      </button>
    </div>
  </ng-container>
</div>

<div
  class="uploader-info pan"
  *ngIf="status.length && uploaderInfo"
  [ngClass]="isMinified ? 'is-minified' : 'is-maximized'"
>
  <header class="header-info pal" [ngClass]="isMinified ? '' : 'is-maximized'">
    <div class="d-flex justify-content-between align-items-center w-100">
      <div class="time-info pl-3">
        <span *ngIf="!isUploading(status)">Upload Completed</span>
        <span *ngIf="isUploading(status)">Uploading {{ getNumUploading(status) }} files</span>
        <span *ngIf="isUploading(status)" class="time-info__remaining"
          >{{ estimatedTime(status) || 0 }}s remaining</span
        >
      </div>
      <div class="summary-info d-flex justify-content-around pr-3" style="width: 240px">
        <div class="info info-success">
          <i class="icon-arrow-up text-success"></i><span>{{ getNumUploaded(status) }} file(s) uploaded</span>
        </div>
        <div class="info info-error">
          <i class="icon-times text-danger"></i><span>{{ getNumError(status) }} errors</span>
        </div>
      </div>
    </div>
    <div class="action-btns position-absolute">
      <i class="icon-arrow-down cursor-pointer" *ngIf="!isMinified" (click)="toogleMinified()"></i>
      <i class="icon-arrow-up cursor-pointer" *ngIf="isMinified" (click)="toogleMinified()"></i>
      <i class="icon-times-circle-solid cursor-pointer" (click)="closeEmitter.emit()"></i>
    </div>
  </header>
  <main class="main-info" *ngIf="!isMinified">
    <section class="file-info cancel">
      <a nohref (click)="cancelEmitter.emit()" class="link text-danger pr-3">Cancel</a>
    </section>
    <section *ngFor="let f of status" class="file-info d-flex">
      <div class="d-flex">
        <div class="pl-3 pr-3" [ngClass]="f.errorMessage ? 'error-icon' : ''">
          <i class="material-icons is-circle is-white is-success mrm mll" *ngIf="f.status === 'complete'">done</i>
          <i class="material-icons is-circle is-white is-error mrm mll" *ngIf="f.status === 'error'">clear</i>
          <span *ngIf="f.status === 'uploading'"><i class="icon-spinner rotate mrm mll"></i></span>
        </div>
        <div class="file-info__text" style="width: 450px">
          {{ shortenFilename(f.name) }}<br />
          <span
            *ngIf="
              f.status === 'error' &&
              f.errorMessage &&
              (f.errorMessage.error.message === 'malware.already_uploaded' ||
                f.errorMessage.error.message === 'error.already_uploaded')
            "
            class="file-info__text-error text-danger"
            >File already uploaded.</span
          >
          <span
            *ngIf="f.status === 'error' && f.errorMessage && f.errorMessage.error.message === 'error.undefined_error'"
            class="file-info__text-error text-danger"
            >File upload error. Please, try again.</span
          >
          <span
            *ngIf="f.status === 'error' && f.errorMessage && f.errorMessage.error.message === 'malware.max_file_size'"
            class="file-info__text-error text-danger"
            >File size cannot exceed 20MB.</span
          >
          <span *ngIf="f.error && !f.errorMessage" class="file-info__text-error text-danger"
            >{{ f.error }} - Error uploading the file</span
          >
          <span
            *ngIf="
              f.status === 'complete' &&
              f.estimatedTime &&
              !f.estimatedTime.error &&
              f.estimatedTime.httpCode === 202 &&
              f.estimatedTime.message === 'error.already_uploaded'
            "
            class="file-info__text-error text-danger"
            >File already uploaded.</span
          >
          <span
            *ngIf="f.status === 'error' && f?.errorMessage?.error?.message === 'Upload malware file is empty'"
            class="file-info__text-error text-danger"
            >Uploaded malware file is empty</span
          >
          <span
            *ngIf="f.status === 'error' && f?.errorMessage?.error === 'file_not_allowed'"
            class="file-info__text-error text-danger"
            >Extension does not match file type</span
          >
        </div>
      </div>
      <div class="pr-3 d-flex justify-content-between" style="width: 50px">
        <i
          class="icon-refresh cursor-pointer refresh-icon"
          *ngIf="f.status === 'error'"
          (click)="reUploadFile.emit(f)"
        ></i>
        <i
          class="icon-delete cursor-pointer delete-icon"
          *ngIf="f.status !== 'uploading'"
          (click)="removeFile.emit(f.id)"
        ></i>
      </div>
    </section>
  </main>
</div>

// src/lib/components/Uploader/index.svelte
<script lang="ts">
  import Client from '$lib/client';
  import { beforeUpload } from '$lib/utils/functions';
  import { Button, InlineLoading, TooltipDefinition } from 'carbon-components-svelte';
  import {
    Add,
    CheckmarkFilled,
    ChevronDown,
    ChevronUp,
    CloseFilled,
    CloseOutline,
    InformationFilled,
    Renew,
    TrashCan,
    Upload
  } from 'carbon-icons-svelte';
  import { currentModule } from '$stores/module';
  import { currentOrganization } from '$stores/organization';
  import { createEventDispatcher } from 'svelte';
  import GenericButton from '$lib/components/Buttons/GenericButton.svelte';

  type StatusFileType = File & {
    name: string;
    status: string;
    id: string;
    estimatedTime: any;
    errorMessage?: any;
    error?: any;
  };

  export let iconDescription =
    'Analyze the behaviour of potential malicious samples such as .exe, .dll, .sys, .doc, .pdf, .com and .zip in our sandbox. Max. file size is 20MB.';

  let fileinput: HTMLInputElement;
  let filesStatus: StatusFileType[] = [];
  let filesObjs: File[] = [];
  let isMinified = true;

  const client = new Client();
  const dispatch = createEventDispatcher();

  function toogleMinified() {
    isMinified = !isMinified;
  }

  function isUploading(status) {
    return status.some((s) => s.status === 'uploading');
  }

  function getNumUploading(status) {
    return status.filter((s) => s.status === 'uploading').length;
  }

  function getNumUploaded(status) {
    return status.filter((s) => s.status === 'complete').length;
  }

  function getNumError(status) {
    return status.filter((s) => s.status === 'error').length;
  }

  function estimatedTime(status) {
    return Math.round(Math.floor(status.map((x) => x.estimatedTime || 0).reduce((a, b) => (a > b ? a : b), 0)));
  }

  function onCloseUploaderStatus() {
    filesStatus = [];
  }

  function shortenFilename(filename: string) {
    return filename.length > 50 ? filename.slice(0, 40) + '...' + filename.slice(-8, 8) : filename;
  }

  function updateFilesObjs(file: StatusFileType, status: any, message?: string) {
    filesStatus = filesStatus.map((f: StatusFileType) => {
      if (f.name === file.name) {
        const { errorMessage, ...rest } = f;
        return {
          ...rest,
          status,
          ...(status !== 'uploading' && errorMessage ? { errorMessage } : {}),
          ...(message ? { errorMessage: { error: { message } } } : {})
        };
      } else {
        return f;
      }
    });
  }

  function getErrorText(file: StatusFileType) {
    const { status, errorMessage, estimatedTime, error = '' } = file;
    if (status === 'error') {
      if (
        errorMessage?.error?.message === 'malware.already_uploaded' ||
        errorMessage?.error?.message === 'error.already_uploaded'
      ) {
        return 'File already uploaded.';
      } else if (errorMessage?.error?.message === 'error.undefined_error') {
        return 'File upload error. Please, try again.';
      } else if (errorMessage?.error?.message === 'malware.max_file_size') {
        return 'File size cannot exceed 20MB.';
      } else if (errorMessage?.error?.message === 'Upload malware file is empty') {
        return 'Upload malware file is empty';
      } else if (errorMessage?.error === 'file_not_allowed') {
        return 'Extension does not match file type';
      } else if (!errorMessage?.error?.message) {
        return `${error} - Error uploading the file`;
      }
    } else if (status === 'complete') {
      if (errorMessage?.error?.message === 'error.already_uploaded') {
        return 'File already uploaded.';
      }
    }
    return '';
  }

  const onFileSelected = (e) => {
    const { files: filesArg } = e.target;

    const files = Array.prototype.slice.call(filesArg); // Files to Array
    const getFileId = (file: File) => `${file.name}:${file.lastModified}:${file.size}`;

    filesObjs = [...filesObjs, ...files];
    filesStatus = [
      ...filesStatus,
      ...files.map((f: StatusFileType) => {
        const { lastModified, name, size, type, webkitRelativePath } = f;
        return { lastModified, name, size, type, webkitRelativePath, status: 'uploading', id: getFileId(f) };
      })
    ];

    files.forEach((f: StatusFileType, index: number) => {
      ((file: StatusFileType, indx) => {
        if (beforeUpload(file)) {
          uploadOneFileOrUrl(file);
        } else {
          updateFilesObjs(file, 'error', 'malware.max_file_size');
        }
      })(f, index);
    });
  };

  async function uploadOneFileOrUrl(fileOrUrl, isUrl = false) {
    try {
      const { data } = await client.files.uploadMalwareFile(
        $currentOrganization.id,
        $currentModule.id,
        $currentModule.moduleName,
        fileOrUrl
      );
      if (data?.message?.includes?.('error')) {
        const isAlreadyUploaded = data?.message === 'error.already_uploaded' ? 'complete' : 'error';
        updateFilesObjs(fileOrUrl, isAlreadyUploaded, data?.message);
      } else {
        updateFilesObjs(fileOrUrl, 'complete');
        dispatch('uploadFile');
      }
    } catch (error) {
      console.log('error to upload: ', error);
    }
  }

  async function reUploadFile(fileObject) {
    updateFilesObjs(fileObject, 'uploading');
    const now = new Date().getTime();
    const getFileId = (file) => `${file.name}:${file.lastModified}:${file.size}`;
    const getFileOrUrlId = (f) => (fileObject.isUrl ? `url:${now}` : getFileId(f));
    filesStatus = filesStatus.map((f) => (f.id === fileObject.id ? { ...f, id: getFileOrUrlId(f) } : f));
    const fileToSend = filesObjs.find((file: File) => file.name === fileObject.name);
    await uploadOneFileOrUrl(fileToSend);
  }

  function removeFile(fileId: string) {
    filesStatus = filesStatus.filter((file: StatusFileType) => file.id !== fileId);
  }
</script>

<GenericButton kind="tertiary" class="mb-2" on:click={() => fileinput.click()}>Upload a sample <Add /></GenericButton>
<TooltipDefinition tooltipText={iconDescription}>
  <GenericButton kind="tertiary">
    <InformationFilled class="upload-info" />
  </GenericButton>
</TooltipDefinition>
<input
  style="display:none"
  type="file"
  accept=".exe, .dll, .sys, .doc, .pdf, .com, .zip, .jpg, .jepg, .png"
  multiple
  on:change={(e) => onFileSelected(e)}
  bind:this={fileinput}
/>

{#if filesStatus.length}
  <div
    class="flex flex-col border-solid border-[1px] border-ctip-dark rounded-t-[5px] fixed bottom-0 right-[60px] w-[560px] z-10"
    class:is-minified={isMinified}
    class:is-maximized={!isMinified}
  >
    <header class="flex h-[60px] bg-ctip-primaryHover text-ctip-white text-sm" class:is-maximized={!isMinified}>
      <div class="flex items-center justify-between w-100">
        <div class="flex flex-col pl-3">
          {#if isUploading(filesStatus)}
            <span>Uploading {getNumUploading(filesStatus)} files</span>
            <span class="text-ctip-gray font-[200]">{estimatedTime(filesStatus) || 0}s remaining</span>
          {:else}
            <span>Upload Completed</span>
          {/if}
        </div>
        <div class="flex justify-around items-center pr-3 w-[240px]">
          <Upload class="text-ctip-successThreat" /><span>{getNumUploaded(filesStatus)} file(s) uploaded</span>
          <CloseOutline class="text-ctip-dangerThreat" /><span>{getNumError(filesStatus)} errors</span>
        </div>
      </div>
      <div class="flex justify-around pt-[3px] w-[46px] right-0 absolute">
        <span on:click={toogleMinified} class="cursor-pointer">
          {#if isMinified}
            <ChevronUp />
          {:else}
            <ChevronDown />
          {/if}
        </span>
        <span on:click={onCloseUploaderStatus} class="cursor-pointer"><CloseOutline /></span>
      </div>
    </header>
    {#if !isMinified}
      <main class="flex flex-col">
        <section class="flex items-center justify-end bg-ctip-grayMiddle pb-[5px]">
          <Button kind="ghost" on:click={onCloseUploaderStatus}>Cancel</Button>
        </section>
        {#each filesStatus as file}
          <section
            class="flex items-center justify-between bg-ctip-white border-b-solid border-b-[1px] border-b-ctip-light pt-[10px] pb-[10px]"
          >
            <div class="flex items-center">
              <div class="pl-3 pr-3" class:error-icon={file.errorMessage}>
                {#if file.status === 'complete'}
                  <CheckmarkFilled class="text-ctip-successThreat" />
                {:else if file.status === 'error'}
                  <CloseFilled class="text-ctip-dangerThreat" />
                {:else if file.status === 'uploading'}
                  <InlineLoading class="text-ctip-grayThreat" />
                {/if}
              </div>
              <div class="text-ctip-gray w-[450px]">
                {shortenFilename(file.name)}<br />
                {#if file.status === 'error' || file.status === 'complete'}
                  <span class="text-ctip-dangerThreat">{getErrorText(file)}</span>
                {/if}
              </div>
              <div class="flex justify-between w-[50px]">
                {#if file.status === 'error'}
                  <span on:click={() => reUploadFile(file)} class="cursor-pointer"><Renew /></span>
                {/if}
                {#if file.status !== 'uploading'}
                  <span on:click={() => removeFile(file.id)} class="cursor-pointer"><TrashCan /></span>
                {/if}
              </div>
            </div>
          </section>
        {/each}
      </main>
    {/if}
  </div>
{/if}

<style>
  :global(svg.upload-info) {
    fill: var(--ctip-interactive);
  }

  :global(button:hover svg.upload-info) {
    fill: var(--ctip-white);
  }
</style>
