// angular/src/app/dashboard/organization/create-module/create-module.component.ts
import { Component, OnInit, OnDestroy, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import { MatStepper } from '@angular/material/stepper';

import { ToastrService } from 'ngx-toastr';

import { getModulesType, ModuleType } from 'app/dashboard/modules-types';
import { OrganizationService } from '../organization.service';
import { ModuleModel } from '../models';

@Component({
  selector: 'app-create-module',
  templateUrl: './create-module.component.html',
  styleUrls: ['./create-module.component.scss']
})
export class CreateModuleComponent implements OnInit, OnDestroy {
  @ViewChild('stepper', { static: false }) private stepper: MatStepper;

  shortNameToSend: string;
  maxShortNameLengthPrefix: number;
  typesList: ModuleType[];
  maxShortNameLength = 8;
  selected: ModuleType;
  subTypesList: ModuleType[];
  subTypeSelected: ModuleType;
  key: string;
  showSubtypeDescription = false;
  hideGlobalDescription = false;
  currentModules: ModuleModel[];
  showForm = false;
  errors: any = {};
  description: string;
  prefix: string;
  organizationType;
  availableModules: any[];
  loading = true;
  placeholder = '';
  loadingCreate = false;
  sources = [];
  stepIndex = 0;

  private _shortName: string;
  private _name: string;
  private readonly destroy$ = new Subject<void>();

  get name() {
    return this._name;
  }
  set name(v) {
    this._name = v;
    this.checkName();
  }

  get shortName() {
    return this._shortName;
  }

  set shortName(v) {
    this._shortName = v;
    this.checkShortName();
  }

  get hasErrors() {
    return Object.keys(this.errors).filter((e) => !!this.errors[e]).length > 0;
  }

  constructor(
    private organizationService: OrganizationService,
    private router: Router,
    private toastrService: ToastrService
  ) {}

  ngOnInit() {
    this.organizationType = this.organizationService.currentOrganization;

    getModulesType()
      .pipe(takeUntil(this.destroy$))
      .subscribe((typesHash) => {
        this.typesList = Object.keys(typesHash).map((e) => {
          const type = typesHash[e];
          type.key = e;
          return type;
        });
        if (this.currentModules) {
          this.checkUniqueModulesPresence();
        }
      });

    this.organizationService
      .getCurrentModules()
      .pipe(takeUntil(this.destroy$))
      .subscribe((d) => {
        this.currentModules = d;
        if (this.typesList) {
          this.checkUniqueModulesPresence();
        }
      });

    this.organizationService
      .getAllowedModules(this.organizationType.id)
      .pipe(takeUntil(this.destroy$))
      .subscribe((res) => {
        this.availableModules = res;
        this.checkAvailableModules();
      });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  checkUniqueModulesPresence() {
    const intelligence = this.currentModules?.filter?.((m) => m.moduleName === 'threat_context');
    const explorer = this.currentModules?.filter?.((m) => m.moduleName === 'explorer');
    this.removeUniqueModulesFromListOfTypes(intelligence, explorer);
  }

  removeUniqueModulesFromListOfTypes(threat_context, explorer) {
    if (threat_context?.length) {
      this.typesList = this.typesList.filter((m) => m.type !== 'threat_context');
    }

    if (explorer?.length) {
      this.typesList = this.typesList.filter((m) => m.type !== 'explorer');
    }
  }

  checkAvailableModules() {
    this.typesList = this.typesList?.filter?.(
      (mod) => this.availableModules.includes(mod.key.toUpperCase()) || mod.key === 'credit_card_25'
    );
    this.loading = false;
  }

  selectType(i: ModuleType) {
    this.selected = i;
    this.showForm = false;
    if (i.type === 'credit_card') {
      this.selected.key = 'credit_cards_full';
      this.selected.prefix = 'CC-';
      this.selected.name = 'Credit cards';
      this.key = this.selected.key;
      this.showForm = true;
      this.subTypesList = null;
      this.subTypeSelected = null;
      this.showSubtypeDescription = false;
      this.hideGlobalDescription = false;
    } else if (i.type === 'custom') {
      this.organizationService
        .getPlugins()
        .pipe(takeUntil(this.destroy$))
        .subscribe((res) => {
          this.sources = res.map((source) => ({ name: source, checked: false }));
          this.key = i.key;
          this.subTypesList = null;
          this.subTypeSelected = null;
          this.showSubtypeDescription = false;
          this.hideGlobalDescription = false;
          this.showForm = true;
        });
    } else {
      this.key = i.key;
      this.showForm = true;
      this.subTypesList = null;
      this.subTypeSelected = null;
      this.showSubtypeDescription = false;
      this.hideGlobalDescription = false;
    }
    this.autoComplete(i);
  }

  selectSubType(i: ModuleType) {
    this.subTypeSelected = i;
    this.showSubtypeDescription = true;
    this.showForm = true;
    this.key = i.key;
    this.autoComplete(i);
  }

  autoComplete(selected: ModuleType) {
    const name = selected.name;
    const namePrefix = name.replace(/\([^\(]*?\)/g, '');
    this.placeholder = namePrefix;
    this._name = this.setDefaultName(name);
    const match = namePrefix.match(/\b(\w)/g);
    this.prefix = selected.prefix;
    let i = this.currentModules.length;
    this.maxShortNameLengthPrefix = this.maxShortNameLength - this.prefix.length;
    this.shortName = match ? match.join('').substr(0, 3) + i : '';
    while (this.checkShortName()) {
      i++;
      this.shortName = match ? match.join('').substr(0, 3) + i : '';
    }
    this.description = selected.description;
  }

  setDefaultName(name: string) {
    if (this.currentModules) {
      const repeated = this.currentModules.filter((e) => {
        return e.name.toLowerCase() === name.toLowerCase();
      }).length;

      if (repeated === 1) {
        const number = name.replace(/[^0-9]/g, '') || '0';
        const count = parseInt(number, 10);
        if (count > 0) {
          name = name.replace(/[0-9]/g, '');
        }
        return this.setDefaultName(`${name}${count + 1}`);
      }
      return name;
    }
  }

  checkName() {
    if (this.currentModules?.filter?.((e) => e.name === this._name).length) {
      this.errors.name = 'There is another module with this name.';
    } else if (this._name.length > 45) {
      this.errors.name = 'Max length is 45 characters.';
    } else if (this._name.length < 6) {
      this.errors.name = 'Min length is 6 characters.';
    } else {
      this.errors.name = null;
    }
  }

  checkShortName() {
    if (this.currentModules?.filter?.((e) => e.shortName === `${this.prefix}${this._shortName}`).length) {
      this.errors.shortName = 'Shortname already in use';
      return true;
    } else if (this.shortName.length > this.maxShortNameLengthPrefix) {
      this.errors.shortName = `This shortname is too long: max ${this.maxShortNameLengthPrefix} characters allowed`;
      return false;
    } else {
      this.errors.shortName = null;
      return false;
    }
  }

  save() {
    if (!this.hasErrors) {
      this.loading = true;
      const organizationId = this.organizationService.currentOrganization.id;
      const organizationEnabled = this.organizationService.currentOrganization.enabled;
      this.shortNameToSend = this.prefix + this.shortName;
      const data = new ModuleModel(
        organizationId,
        this.key.toUpperCase(),
        this.name,
        this.shortNameToSend,
        organizationEnabled
      );
      if (this.key.toLowerCase() === 'custom') {
        const selectedPlugins = this.sources.filter((source) => source.checked).map((item) => item.name);
        data.plugins = selectedPlugins;
      }
      this.organizationService.createModule(organizationId, data).subscribe(
        (data) => {
          const m = data as ModuleModel;
          const url = this.getRedirectUrl(m, organizationId);
          this.organizationService.refreshCacheModules(true, m);
          this.organizationService.setCurrentModule(m);
          this.organizationService.setCreateModuleMessageSubject(this.name);
          this.loading = false;
          this.router.navigate([url]);
        },
        (err) => {
          this.loading = false;
          this.toastrService.error(
            err.error.message === 'error.module_create_contract'
              ? 'To create the module you should review your product agreement with Customer Succes'
              : err.error.field,
            'Error'
          );
        }
      );
    }
  }

  getRedirectUrl(module, organizationId) {
    const url =
      module.moduleName === 'threat_context' || module.type === 'THREAT_CONTEXT' ? 'threat_context/actors' : 'settings';
    return `/dashboard/organizations/${organizationId}/modules/${module.id}/${url}`;
  }

  goBack(stepper: MatStepper) {
    this.stepper.previous();
  }

  goForward(stepper: MatStepper) {
    this.stepper.next();
  }

  onStepChange(event: any) {
    this.stepIndex = event.selectedIndex;
  }

  canMoveToNameStep() {
    const selected = this.sources.filter((s) => s.checked);
    return selected.length > 0;
  }

  canMoveToSummaryStep() {
    return this.name && this.shortName;
  }

  getNextTooltip() {
    if (this.stepIndex === 0 && !this.canMoveToNameStep()) {
      return 'You need to select at least one';
    } else if (this.stepIndex === 1 && !this.canMoveToSummaryStep()) {
      return 'Please provide a valid name and short-name';
    } else {
      return '';
    }
  }
}

<!-- MAIN HEADER -->
<div class="mt-4 pb-3 border-bottom mb-3">
  <div class="main-header row align-items-end clearfix">
    <div class="main-header-left col float-left">
      <h6 class="text-muted text-uppercase text-90 font-weight-bold mb-3 mt-1">Create Module</h6>
      <h5 class="text-dark mb-0">Create</h5>
    </div>
  </div>
</div>
<div class="row mb-4">
  <!-- ITEMS MENU -->
  <div class="col-md-3">
    <div class="card">
      <div class="card-header clearfix">
        <h6 class="mb-0">Select Module Type</h6>
      </div>
      <div class="card-body p-0">
        <ul class="list-group list-group-flush">
          <div
            class="card-section mt-4 mr-5 ml-5 mb-5 d-flex flex-column justify-content-center align-items-center loading-container"
            *ngIf="loading"
          >
            <div class="text-primary mb-2 font-weight-bold">Loading...</div>
            <i class="icon-spinner rotate"></i>
          </div>
        </ul>
        <ul class="list-group list-group-flush" *ngIf="!loading">
          <li
            class="list-group-item d-flex justify-content-between align-items-center"
            *ngFor="let item of typesList"
            [ngClass]="{ selected: item === selected }"
            (click)="selectType(item)"
          >
            <span>
              <img class="mr-3 float-left" [src]="item.image" />
              <h6 class="float-left mt-1">{{ item.name }}</h6>
            </span>
            <i class="icon-angle-right float-right"></i>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- ITEMS CONTENT -->
  <div class="col-md-9">
    <div class="card d-flex justify-content-center align-items-center h-100" *ngIf="!showForm && selected">
      <i class="icon-spinner rotate"></i>
    </div>
    <div class="card" *ngIf="showForm && !hideGlobalDescription">
      <div class="card-header clearfix">
        <h6 class="mb-0">Fill the fields</h6>
      </div>
      <div class="card-body">
        <div class="pb-4 border-bottom mb-4">{{ description }}</div>
        <div *ngIf="showForm && !showSubtypeDescription && key !== 'custom'">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label>Name:</label>
                <input
                  type="text"
                  class="form-control"
                  [placeholder]="placeholder"
                  [(ngModel)]="name"
                  [ngClass]="{ error: errors.name }"
                  name="name"
                  [disabled]="key === 'explorer'"
                />
                <span class="error" *ngIf="errors.name">{{ errors.name }}</span>
              </div>
            </div>
            <div class="col-md-6">
              <div class="input-group">
                <label class="w-100 d-block">Short-Name:</label>
                <div class="input-group-prepend">
                  <span class="input-group-text rounded-left">{{ prefix }}</span>
                </div>
                <input
                  type="text"
                  class="form-control"
                  placeholder="Short-name"
                  [(ngModel)]="shortName"
                  [ngClass]="{ error: errors.shortName }"
                  name="shortName"
                />
              </div>
              <span class="error" *ngIf="errors.shortName">{{ errors.shortName }}</span>
            </div>
          </div>
        </div>
        <div *ngIf="showForm && !showSubtypeDescription && key === 'custom'">
          <mat-stepper class="mat-stepper" linear #stepper (selectionChange)="onStepChange($event)">
            <mat-step [completed]="canMoveToNameStep()">
              <ng-template matStepLabel
                ><div>
                  <span>Sources &nbsp;&nbsp;&nbsp;&nbsp;<br /></span
                  ><span *ngIf="!canMoveToNameStep()" class="conditions-text">Select at least one</span>
                </div></ng-template
              >
              <div class="card">
                <div class="card-body p-0 height-list" style="height: 350px; overflow: scroll">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th style="font-size: 12px">Name</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody *ngIf="sources?.length != 0">
                      <tr *ngFor="let transformada of sources; let i = index">
                        <td class="vertical-middle">
                          <p class="mb-0">{{ transformada.name }}</p>
                        </td>
                        <td class="vertical-middle td-center td-80">
                          <mat-slide-toggle [(ngModel)]="transformada.checked"></mat-slide-toggle>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </mat-step>
            <mat-step [completed]="canMoveToSummaryStep()">
              <ng-template matStepLabel
                ><div>
                  <span>Module Name &nbsp;&nbsp;&nbsp;&nbsp;<br /> </span>
                  <span *ngIf="!canMoveToSummaryStep() && stepIndex === 1" class="conditions-text"
                    >Fill in the boxes</span
                  >
                </div></ng-template
              >

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Name:</label>
                    <input
                      type="text"
                      class="form-control"
                      [placeholder]="placeholder"
                      [(ngModel)]="name"
                      [ngClass]="{ error: errors.name }"
                      name="name"
                    />
                    <span class="error" *ngIf="errors.name">{{ errors.name }}</span>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="input-group">
                    <label class="w-100 d-block">Short-Name:</label>
                    <div class="input-group-prepend">
                      <span class="input-group-text rounded-left">{{ prefix }}</span>
                    </div>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Short-name"
                      [(ngModel)]="shortName"
                      [ngClass]="{ error: errors.shortName }"
                      name="shortName"
                    />
                  </div>
                  <span class="error" *ngIf="errors.shortName">{{ errors.shortName }}</span>
                </div>
              </div></mat-step
            >
            <mat-step>
              <ng-template matStepLabel
                ><div>
                  <span>Summary</span>
                </div></ng-template
              >
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Name:</label>
                    <input
                      type="text"
                      class="form-control"
                      [placeholder]="placeholder"
                      [(ngModel)]="name"
                      [ngClass]="{ error: errors.name }"
                      name="name"
                      disabled
                    />
                    <span class="error" *ngIf="errors.name">{{ errors.name }}</span>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="input-group">
                    <label class="w-100 d-block">Short-Name:</label>
                    <div class="input-group-prepend">
                      <span class="input-group-text rounded-left">{{ prefix }}</span>
                    </div>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Short-name"
                      [(ngModel)]="shortName"
                      [ngClass]="{ error: errors.shortName }"
                      name="shortName"
                      disabled
                    />
                  </div>
                  <span class="error" *ngIf="errors.shortName">{{ errors.shortName }}</span>
                </div>
              </div>
              <div class="card">
                <div class="card-body p-0 height-list" style="height: 350px; overflow: scroll">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th style="font-size: 12px">Name</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody *ngIf="sources?.length != 0">
                      <tr *ngFor="let transformada of sources; let i = index">
                        <td class="vertical-middle">
                          <p class="mb-0">{{ transformada.name }}</p>
                        </td>
                        <td class="vertical-middle td-center td-80">
                          <mat-slide-toggle disabled [checked]="transformada.checked"></mat-slide-toggle>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div></div
            ></mat-step>
          </mat-stepper>
        </div>
      </div>
      <div class="card-footer clearfix">
        <button
          *ngIf="key !== 'custom'"
          data-bv="create"
          class="btn btn-light btn-sm border text-primary float-right"
          type="submit"
          [disabled]="errors.name || errors.shortName"
          (click)="save()"
        >
          Create
        </button>
        <div class="d-flex justify-content-end">
          <button
            class="btn btn-light btn-sm border text-primary float-right mr-2"
            *ngIf="key === 'custom' && (stepIndex === 1 || stepIndex === 2)"
            (click)="goBack(stepper)"
            type="button"
          >
            Previous
          </button>
          <button
            class="btn btn-light btn-sm border text-primary float-right mr-2"
            *ngIf="key === 'custom' && (stepIndex === 0 || stepIndex === 1)"
            (click)="goForward(stepper)"
            type="button"
            [ngbTooltip]="getNextTooltip()"
            [ngClass]="!canMoveToNameStep() || !canMoveToSummaryStep() ? 'btn-disabled' : ''"
          >
            Next
          </button>

          <button
            class="btn btn-primary btn-sm border float-right"
            data-bv="create"
            *ngIf="key === 'custom' && stepIndex === 2"
            type="submit"
            (click)="save()"
          >
            Create
          </button>
        </div>
      </div>
    </div>
    <!-- MODULE CARDS -->
    <div class="card" *ngIf="subTypesList">
      <div class="card-header d-flex justify-content-between">
        <button
          class="btn btn-light border btn-sm text-primary"
          *ngFor="let item of subTypesList"
          [ngClass]="{ selected: item === subTypeSelected }"
          (click)="selectSubType(item)"
        >
          <i class="icon-credit-card"></i>
          <span class=""> {{ item.name }}</span>
        </button>
      </div>
      <div class="card-body" *ngIf="showSubtypeDescription">
        <div class="pb-4 border-bottom mb-4">{{ description }}</div>
        <div *ngIf="showSubtypeDescription">
          <form>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Name:</label>
                  <input
                    type="text"
                    class="form-control"
                    [placeholder]="placeholder"
                    [(ngModel)]="name"
                    [ngClass]="{ error: errors.name }"
                    name="name"
                  />

                  <span class="error" *ngIf="errors.name">{{ errors.name }}</span>
                </div>
              </div>
              <div class="col-md-6">
                <div class="input-group">
                  <label class="w-100 d-block">Short-Name:</label>
                  <div class="input-group-prepend">
                    <span class="input-group-text rounded-left">{{ prefix }}</span>
                  </div>
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Short-name"
                    [(ngModel)]="shortName"
                    [ngClass]="{ error: errors.shortName }"
                    name="shortName"
                  />
                </div>
                <span class="error" *ngIf="errors.shortName">{{ errors.shortName }}</span>
              </div>
            </div>
            <button
              class="btn btn-light border btn-sm text-primary float-right"
              type="submit"
              [disabled]="errors.name || errors.shortName || loadingCreate"
              (click)="save()"
            >
              <i class="icon-spinner rotate" *ngIf="loadingCreate"></i>
              Create
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

// src/lib/components/CRUD_Modules/CreateModules/CreateModule.svelte
<script lang="ts">
  import type Module from '$lib/types/module';
  import type { ModuleModelType, ModuleType } from '$lib/types/module';
  import { currentOrganization } from '$stores/organization';
  import { modulesStore, moduleCacheStore } from '$stores/module';
  import { Loading, ProgressIndicator, ProgressStep, SkeletonPlaceholder, TextArea } from 'carbon-components-svelte';
  import Client from '$lib/client';
  import notifications from '$stores/notification';
  import GenericButton from '$lib/components/Buttons/GenericButton.svelte';
  import { goto } from '$app/navigation';
  import InfoCardForm from '../../Card/InfoCardForm.svelte';
  import { MODULE_NAME } from '$lib/constants/modules';
  import Fields from '../Fields.svelte';
  import Sources from '../Sources.svelte';

  const client = new Client();

  type TransformadaType = {
    name: string;
    checked: boolean;
  };

  export let selectedModule: ModuleType;
  export let redirectAfterCreation: boolean = true;
  export let onFinishedCreationCallback = () => {};

  let isLoading = false;
  let isLoadingSources = false;
  let showForm = false;
  let key: string;
  let sources: TransformadaType[] = [];
  let placeholder = '';
  let shortName: string;
  let firstDataLoad = false;
  let name: string;
  let prefix: string;
  let strictTermText: string;
  let maxShortNameLengthPrefix: number;
  let maxShortNameLength = 8;
  let errors: any = {};
  let shortNameToSend: string;
  let hideCCForCreditCards = false;
  let hidePasswordsForCredentials = false;
  let currentIndex = 0;

  $: shortName && checkShortName();
  $: name !== undefined && checkName();
  $: selectType(selectedModule);

  async function selectType(i: ModuleType) {
    sources = [];
    selectedModule = i;
    key = i?.key;
    showForm = false;
    if (i?.type === 'credit_card') {
      selectedModule = {
        ...selectedModule,
        key: 'credit_cards_full',
        prefix: 'CC-',
        name: 'Credit cards'
      };
      key = selectedModule.key;
      showForm = true;
    } else if (i?.type === 'custom') {
      isLoadingSources = true;
      const { data } = await client.organization.getPlugins();
      sources = data.map((source) => ({ name: source, checked: false }));
      isLoadingSources = false;
    } else {
      showForm = true;
    }
    autoComplete(i);
  }

  function autoComplete(selected: ModuleType) {
    const sname = selected?.name;
    const namePrefix = sname?.replace(/\([^\(]*?\)/g, '');
    placeholder = namePrefix;
    name = setDefaultName(sname);
    const match = namePrefix?.match(/\b(\w)/g);
    prefix = selected?.prefix;
    let i = $modulesStore.length;
    maxShortNameLengthPrefix = maxShortNameLength - prefix?.length;
    shortName = match ? match.join('').substr(0, 3) + i : '';
    while (checkShortName()) {
      i++;
      shortName = match ? match.join('').substr(0, 3) + i : '';
    }
  }

  function setDefaultName(name: string) {
    if ($modulesStore) {
      const repeated = $modulesStore.filter((e) => e.name?.toLowerCase() === name?.toLowerCase()).length;

      if (repeated === 1) {
        const number = name.replace(/[^0-9]/g, '') || '0';
        const count = parseInt(number, 10);
        if (count > 0) {
          name = name.replace(/[0-9]/g, '');
        }
        return setDefaultName(`${name}${count + 1}`);
      }
      return name;
    }
  }

  function checkName() {
    if ($modulesStore?.filter?.((e) => e.name === name).length) {
      errors.name = 'There is another module with this name.';
    } else if (name.length > 45) {
      errors.name = 'Max length is 45 characters.';
    } else if (name.length < 6) {
      errors.name = 'Min length is 6 characters.';
    } else {
      errors.name = null;
    }
  }

  function checkShortName() {
    if ($modulesStore?.filter?.((e) => e.shortName === `${prefix}${shortName}`).length) {
      errors.shortName = 'Shortname already in use';
      return true;
    } else if (shortName.length > maxShortNameLengthPrefix) {
      errors.shortName = `This shortname is too long: max ${maxShortNameLengthPrefix} characters allowed`;
      return false;
    } else {
      errors.shortName = null;
      return false;
    }
  }

  async function save() {
    if (!Object.keys(errors).filter((e) => !!errors[e]).length) {
      isLoading = true;
      shortNameToSend = `${prefix}${shortName}`;
      const data: ModuleModelType = {
        name,
        ...(key === 'credentials' ? { firstDataLoad } : {}),
        ...(key === 'credentials' ? { hidePasswords: hidePasswordsForCredentials } : {}),
        ...(key === 'credit_cards_full' ? { hideCC: hideCCForCreditCards } : {}),
        shortName: shortNameToSend,
        moduleStrictTokens: strictTermText?.split(/[\n]+/),
        organizationId: $currentOrganization.id,
        enabled: $currentOrganization.enabled,
        type: key.toUpperCase(),
        demoMode: false,
        plugins:
          key.toLowerCase() === 'custom' ? sources.filter((source) => source.checked).map((item) => item.name) : []
      };
      try {
        const newModule = await client.organization.createModule($currentOrganization.id, data);
        const url = getRedirectUrl(newModule);
        await moduleCacheStore.fetchModules($currentOrganization.id);
        isLoading = false;
        if (redirectAfterCreation) await goto(url);
        onFinishedCreationCallback();
      } catch (err) {
        isLoading = false;
        notifications.notify({
          kind: 'error',
          title:
            err.error.message === 'error.module_create_contract'
              ? 'To create the module you should review your product agreement with Customer Succes'
              : err.error.field
        });
      }
    }
  }

  function getRedirectUrl(module: Module) {
    const URL_PATH_MAP = {
      [MODULE_NAME.THREAT_CONTEXT]: 'threat_context/actors',
      [MODULE_NAME.SOCIAL_MEDIA]: 'settings/terms',
      [MODULE_NAME.CUSTOM]: 'settings/terms'
    };
    const URL_DEFAULT = 'settings/parameters';
    const url = URL_PATH_MAP[module.moduleName] || URL_DEFAULT;
    return `/dashboard/organizations/${$currentOrganization.id}/modules/${module.id}/${url}`;
  }
</script>

{#if isLoading}
  <Loading />
{:else if selectedModule}
  <InfoCardForm title="Fill the fields">
    <div class="flex flex-col my-4 mx-4 w-full">
      <div class="pb-4">{selectedModule.description}</div>
      <div class="border-bottom w-full" />
      {#if key === 'custom'}
        <ProgressIndicator bind:currentIndex spaceEqually preventChangeOnClick class="w-full">
          <ProgressStep complete label="Sources" description="Select a source at least" />
          <ProgressStep complete label="Module Name" description="Module name" />
          <ProgressStep complete label="Summary" description="The summary" />
        </ProgressIndicator>
        {#if currentIndex === 0}
          {#if isLoadingSources && !sources.length}
            <SkeletonPlaceholder class="h-80 w-full" />
          {:else}
            <Sources bind:sources />
          {/if}
        {:else if currentIndex === 1}
          <Fields bind:name bind:shortName bind:key bind:prefix bind:placeholder {errors} />
          <TextArea labelText="Strict Term:" bind:value={strictTermText} />
        {:else if currentIndex === 2}
          <TextArea disabled labelText="Strict Term:" bind:value={strictTermText} />
          <Fields bind:name bind:shortName bind:key bind:prefix bind:placeholder {errors} disabled />
          <Sources bind:sources disabled />
        {/if}
      {:else if showForm}
        <Fields
          bind:name
          bind:shortName
          bind:key
          bind:prefix
          bind:placeholder
          bind:hidePasswordsForCredentials
          bind:hideCVVForCreditCards={hideCCForCreditCards}
          bind:firstDataLoad
          {errors}
        />
        {#if key !== 'explorer' && key !== 'threat_context'}
          <TextArea labelText="Strict Term:" bind:value={strictTermText} />
        {/if}
      {/if}
    </div>
    <svelte:fragment slot="actions-form">
      {#if key !== 'custom'}
        <GenericButton kind="primary" on:click={save} disabled={errors.name || errors.shortName}>Create</GenericButton>
      {:else}
        {#if key === 'custom' && (currentIndex === 1 || currentIndex === 2)}
          <GenericButton
            on:click={() => !errors?.name && !errors?.shortName && currentIndex--}
            class={errors.name || errors.shortName ? 'cursor-not-allowed opacity-50' : ''}>Previous</GenericButton
          >
        {/if}
        {#if key === 'custom' && (currentIndex === 0 || currentIndex === 1)}
          <GenericButton
            on:click={() =>
              ((currentIndex === 0 && sources?.filter((s) => s.checked).length) ||
                (currentIndex === 1 && !errors.name && !errors.shortName)) &&
              currentIndex++}
            kind="primary"
            class={!sources?.filter((s) => s.checked).length ||
            (currentIndex === 1 && (errors.name || errors.shortName))
              ? `cursor-not-allowed opacity-50 bx--btn--icon-only bx--tooltip__trigger bx--tooltip--a11y bx--tooltip--align-start ${
                  currentIndex === 0 ? 'bx--btn--icon-only--left' : ''
                }`
              : ''}
          >
            {#if currentIndex === 0 && !sources.filter((s) => s.checked).length}
              <span class:bx--assistive-text={true}>You need to select at least one</span>
            {/if}
            Next
          </GenericButton>
        {/if}
        {#if key === 'custom' && currentIndex === 2}
          <GenericButton on:click={save} disabled={errors.name || errors.shortName} kind="primary">Create</GenericButton
          >
        {/if}
      {/if}
    </svelte:fragment>
  </InfoCardForm>
{/if}
