// src/lib/components/LabelItem/LabelItem.svelte
<script lang="ts">
  import { setColors } from '$lib/utils/functions';
  import { Tag } from 'carbon-components-svelte';

  let _label: any;
  export let label = undefined;
  export let labelProperty = undefined;
  export let customBg = undefined;
  export let filter = false;

  $: if (label) {
    _label = label;

    if ((label.background_color && !label.bgColorHex) || (label.bgColor && label.textColor)) {
      const background = label.background_color ? label.background_color : label.bgColor;
      const isWhite = background === 0xffffff ? 0xeeeeee : background;
      const colorObject = setColors(isWhite, 'rgb');

      _label.background = colorObject.background;
      _label.color = colorObject.color;
      _label.weight = colorObject.weight;
      _label.border = `3px solid ${colorObject.background}`;
    }
    if (!label.background_color && label.bgColorHex) {
      _label.background = label.bgColorHex;
      _label.color = label.textColorHex;
      _label.weight = '500';
      _label.border = `3px solid ${_label.background}`;
    }
    if (labelProperty) {
      _label.name = label[labelProperty];
    }
  }
</script>

<div style="--label-background-color: {customBg ?? _label.background}">
  <Tag
    on:close
    on:click
    {filter}
    type="outline"
    class="[&_span]:whitespace-nowrap [&_span]:text-ellipsis [&_span]:overflow-hidden"
  >
  <span title={_label.name || _label.label}>
    {_label.name || _label.label}
  </span>
  </Tag>
</div>

<style>
  div :global(.bx--tag--outline) {
    box-shadow: inset 0 0 0 3px var(--label-background-color);
    font-size: 10px;
    font-weight: bold;
    margin: 0.01rem;
  }
</style>

// angular/src/app/dashboard/module-sections/shared/table/table-tools/label-item/label-item.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { setColors } from 'app/utils/functions';

@Component({
  selector: 'app-label-item',
  templateUrl: './label-item.component.html',
  styleUrls: ['./label-item.component.scss']
})
export class LabelItemComponent {
  _label: any;
  @Input() labelProperty: string;

  @Input()
  set label(labelValue) {
    this._label = labelValue;
    if ((labelValue.background_color && !labelValue.bgColorHex) || (labelValue.bgColor && labelValue.textColor)) {
      const background = labelValue.background_color ? labelValue.background_color : labelValue.bgColor;
      const isWhite = background === 0xffffff ? 0xeeeeee : background;
      const colorObject = setColors(isWhite, 'rgb');
      this._label.background = this.sanitizer.bypassSecurityTrustStyle(colorObject.background);
      this._label.color = this.sanitizer.bypassSecurityTrustStyle(colorObject.color);
      this._label.weight = this.sanitizer.bypassSecurityTrustStyle(colorObject.weight);
      this._label.border = this.sanitizer.bypassSecurityTrustStyle('3px solid ' + colorObject.background);
    }
    if (!labelValue.background_color && labelValue.bgColorHex) {
      this._label.background = labelValue.bgColorHex;
      this._label.color = labelValue.textColorHex;
      this._label.weight = '500';
      this._label.border = '3px solid ' + this._label.background;
    }
    if (this.labelProperty) {
      this._label.name = labelValue[this.labelProperty];
    }
  }

  get label() {
    return this._label;
  }

  constructor(private sanitizer: DomSanitizer) {}
}

<span class="badge mr-1" [style.border-color]="_label.background">
  {{ label.name || label.label }}
</span>
